version: '3'
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:

      - ..:/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python app_db.py # Replace with your actual command to run the Python application
