"""Dictionary of words for hangman game"""


words = {
    1: [
        "AFGHANISTAN",
        "ALBANIA",
        "ALGERIA",
        "ANDORRA",
        "ANGOLA",
        "ARGENTINA",
        "ARMENIA",
        "BAHAMAS",
        "BAHRAIN",
        "BANGLADESH",
        "BARBADOS",
        "BELARUS",
        "BELGIUM",
        "BELIZE",
        "BENIN",
        "BHUTAN",
        "CHINA",
        "CHAD",
        "MACEDONIA",
        "NEPAL",
        "INDIA",
        "PAKISTAN",
        "BHUTAN",
        "MALDIVES",
    ],
    2: [
        "BABOON",
        "BADGER",
        "BAT",
        "BEAR",
        "BEAVER",
        "CAMEL",
        "CAT",
        "CLAM",
        "COBRA",
        "COUGAR",
        "COYOTE",
        "CROW",
        "ECHIDNA",
        "ELEPHANT",
        "FERRET",
        "FOX",
        "FROG",
        "GOAT",
        "GOOSE",
        "HAWK",
        "LION",
        "LIZARD",
        "LLAMA",
        "MOLE",
        "MONKEY",
        "MOOSE",
        "MOUSE",
        "MULE",
        "NEWT",
        "OTTER",
        "OWL",
        "PANDA",
        "PARROT",
        "PIGEON",
        "PYTHON",
        "RABBIT",
        "RAM",
        "RAT",
        "RAVEN",
        "RHINO",
        "SALMON",
        "SEAL",
        "SHARK",
        "SHEEP",
        "SKUNK",
        "SLOTH",
        "SNAKE",
        "SPIDER",
        "STORK",
        "SWAN",
        "TIGER",
        "TOAD",
        "TROUT",
        "TURKEY",
        "TURTLE",
        "WEASEL",
        "WHALE",
        "WOLF",
        "WOMBAT",
        "ZEBRA",
    ],
    3: [
        "BANANA",
        "APPLE",
        "MANGO",
        "ORANGE",
        "GRAPES",
        "PINEAPPLE",
        "PAPAYA",
        "GUAVA",
        "WATERMELON",
        "KIWI",
        "PEAR",
        "LEMON",
        "CHERRY",
        "STRAWBERRY",
        "BLUEBERRY",
        "PEACH",
        "PLUM",
        "APRICOT",
        "AVOCADO",
        "BLACKBERRY",
        "COCONUT",
        "FIG",
        "GRAPEFRUIT",
        "JACKFRUIT",
        "LYCHEE",
        "POMEGRANATE",
        "RASPBERRY",
        "STARFRUIT",
        "TANGERINE",
        "TOMATO",
        "WATERMELON",
    ],
}


def get_categories_enumerated(categories: dict):
    for cat in enumerate(categories, 1):
        print(cat)
    
        
get_categories_enumerated(categories=words)